services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volume_postgres:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
volumes:
  node_modules:
  volume_postgres:
  volume_pgadmin:
networks:
  snowboard_default:
    external: true
